// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: flow/protos/data.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoding int32

const (
	Encoding_JSON     Encoding = 0
	Encoding_PROTOBUF Encoding = 1
	Encoding_TEXT     Encoding = 2
	Encoding_BINARY   Encoding = 3
	Encoding_CUSTOM   Encoding = 4
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "JSON",
		1: "PROTOBUF",
		2: "TEXT",
		3: "BINARY",
		4: "CUSTOM",
	}
	Encoding_value = map[string]int32{
		"JSON":     0,
		"PROTOBUF": 1,
		"TEXT":     2,
		"BINARY":   3,
		"CUSTOM":   4,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_protos_data_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_flow_protos_data_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_flow_protos_data_proto_rawDescGZIP(), []int{0}
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serialized    []byte                 `protobuf:"bytes,1,opt,name=serialized,proto3" json:"serialized,omitempty"`
	Encoding      Encoding               `protobuf:"varint,2,opt,name=encoding,proto3,enum=wings.flow.v1.Encoding" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_flow_protos_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_flow_protos_data_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetSerialized() []byte {
	if x != nil {
		return x.Serialized
	}
	return nil
}

func (x *Data) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_JSON
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Context       *Data                  `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_flow_protos_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_flow_protos_data_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetContext() *Data {
	if x != nil {
		return x.Context
	}
	return nil
}

type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Result_Data
	//	*Result_Error
	Payload       isResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_flow_protos_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_flow_protos_data_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetPayload() isResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Result) GetData() *Data {
	if x != nil {
		if x, ok := x.Payload.(*Result_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Result) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Result_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResult_Payload interface {
	isResult_Payload()
}

type Result_Data struct {
	Data *Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type Result_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Result_Data) isResult_Payload() {}

func (*Result_Error) isResult_Payload() {}

var File_flow_protos_data_proto protoreflect.FileDescriptor

const file_flow_protos_data_proto_rawDesc = "" +
	"\n" +
	"\x16flow/protos/data.proto\x12\rwings.flow.v1\"[\n" +
	"\x04Data\x12\x1e\n" +
	"\n" +
	"serialized\x18\x01 \x01(\fR\n" +
	"serialized\x123\n" +
	"\bencoding\x18\x02 \x01(\x0e2\x17.wings.flow.v1.EncodingR\bencoding\"P\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\acontext\x18\x02 \x01(\v2\x13.wings.flow.v1.DataR\acontext\"l\n" +
	"\x06Result\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x13.wings.flow.v1.DataH\x00R\x04data\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x14.wings.flow.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload*D\n" +
	"\bEncoding\x12\b\n" +
	"\x04JSON\x10\x00\x12\f\n" +
	"\bPROTOBUF\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\n" +
	"\n" +
	"\x06BINARY\x10\x03\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x04B'Z%github.com/ligustah/wings/flow/protosb\x06proto3"

var (
	file_flow_protos_data_proto_rawDescOnce sync.Once
	file_flow_protos_data_proto_rawDescData []byte
)

func file_flow_protos_data_proto_rawDescGZIP() []byte {
	file_flow_protos_data_proto_rawDescOnce.Do(func() {
		file_flow_protos_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_protos_data_proto_rawDesc), len(file_flow_protos_data_proto_rawDesc)))
	})
	return file_flow_protos_data_proto_rawDescData
}

var file_flow_protos_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flow_protos_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flow_protos_data_proto_goTypes = []any{
	(Encoding)(0),  // 0: wings.flow.v1.Encoding
	(*Data)(nil),   // 1: wings.flow.v1.Data
	(*Error)(nil),  // 2: wings.flow.v1.Error
	(*Result)(nil), // 3: wings.flow.v1.Result
}
var file_flow_protos_data_proto_depIdxs = []int32{
	0, // 0: wings.flow.v1.Data.encoding:type_name -> wings.flow.v1.Encoding
	1, // 1: wings.flow.v1.Error.context:type_name -> wings.flow.v1.Data
	1, // 2: wings.flow.v1.Result.data:type_name -> wings.flow.v1.Data
	2, // 3: wings.flow.v1.Result.error:type_name -> wings.flow.v1.Error
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_flow_protos_data_proto_init() }
func file_flow_protos_data_proto_init() {
	if File_flow_protos_data_proto != nil {
		return
	}
	file_flow_protos_data_proto_msgTypes[2].OneofWrappers = []any{
		(*Result_Data)(nil),
		(*Result_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_protos_data_proto_rawDesc), len(file_flow_protos_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_protos_data_proto_goTypes,
		DependencyIndexes: file_flow_protos_data_proto_depIdxs,
		EnumInfos:         file_flow_protos_data_proto_enumTypes,
		MessageInfos:      file_flow_protos_data_proto_msgTypes,
	}.Build()
	File_flow_protos_data_proto = out.File
	file_flow_protos_data_proto_goTypes = nil
	file_flow_protos_data_proto_depIdxs = nil
}
