// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: flow/protos/event.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterruptCause int32

const (
	InterruptCause_INTERRUPT_CAUSE_UNKNOWN           InterruptCause = 0
	InterruptCause_INTERRUPT_CAUSE_CANCELED          InterruptCause = 1
	InterruptCause_INTERRUPT_CAUSE_DEADLINE_EXCEEDED InterruptCause = 2
)

// Enum value maps for InterruptCause.
var (
	InterruptCause_name = map[int32]string{
		0: "INTERRUPT_CAUSE_UNKNOWN",
		1: "INTERRUPT_CAUSE_CANCELED",
		2: "INTERRUPT_CAUSE_DEADLINE_EXCEEDED",
	}
	InterruptCause_value = map[string]int32{
		"INTERRUPT_CAUSE_UNKNOWN":           0,
		"INTERRUPT_CAUSE_CANCELED":          1,
		"INTERRUPT_CAUSE_DEADLINE_EXCEEDED": 2,
	}
)

func (x InterruptCause) Enum() *InterruptCause {
	p := new(InterruptCause)
	*p = x
	return p
}

func (x InterruptCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterruptCause) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_protos_event_proto_enumTypes[0].Descriptor()
}

func (InterruptCause) Type() protoreflect.EnumType {
	return &file_flow_protos_event_proto_enumTypes[0]
}

func (x InterruptCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterruptCause.Descriptor instead.
func (InterruptCause) EnumDescriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{0}
}

type StartReason int32

const (
	StartReason_START_REASON_UNKNOWN StartReason = 0
	StartReason_START_REASON_INIT    StartReason = 1
	StartReason_START_REASON_RESUME  StartReason = 2
	StartReason_START_REASON_RETRY   StartReason = 3
)

// Enum value maps for StartReason.
var (
	StartReason_name = map[int32]string{
		0: "START_REASON_UNKNOWN",
		1: "START_REASON_INIT",
		2: "START_REASON_RESUME",
		3: "START_REASON_RETRY",
	}
	StartReason_value = map[string]int32{
		"START_REASON_UNKNOWN": 0,
		"START_REASON_INIT":    1,
		"START_REASON_RESUME":  2,
		"START_REASON_RETRY":   3,
	}
)

func (x StartReason) Enum() *StartReason {
	p := new(StartReason)
	*p = x
	return p
}

func (x StartReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartReason) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_protos_event_proto_enumTypes[1].Descriptor()
}

func (StartReason) Type() protoreflect.EnumType {
	return &file_flow_protos_event_proto_enumTypes[1]
}

func (x StartReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartReason.Descriptor instead.
func (StartReason) EnumDescriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{1}
}

// *
// The `WorkflowStatus` enum represents the status of a workflow run.
type WorkflowStatus int32

const (
	// The status of the workflow is unknown. This is the default value.
	WorkflowStatus_WORKFLOW_STATUS_UNKNOWN WorkflowStatus = 0
	// The workflow is currently running.
	WorkflowStatus_WORKFLOW_STATUS_RUNNING WorkflowStatus = 1
	// The workflow has successfully finished.
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED WorkflowStatus = 2
	// The workflow has permanently failed to complete.
	WorkflowStatus_WORKFLOW_STATUS_FAILED WorkflowStatus = 3
	// The workflow is temporarily on hold.
	WorkflowStatus_WORKFLOW_STATUS_SUSPENDED WorkflowStatus = 4
	// The workflow is in backoff state due to a failed attempt.
	WorkflowStatus_WORKFLOW_STATUS_BACKOFF WorkflowStatus = 5
	// The workflow has been added to a queue, and is waiting to get executed.
	WorkflowStatus_WORKFLOW_STATUS_QUEUED WorkflowStatus = 6
	// The workflow has been cancelled.
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED WorkflowStatus = 7
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNKNOWN",
		1: "WORKFLOW_STATUS_RUNNING",
		2: "WORKFLOW_STATUS_COMPLETED",
		3: "WORKFLOW_STATUS_FAILED",
		4: "WORKFLOW_STATUS_SUSPENDED",
		5: "WORKFLOW_STATUS_BACKOFF",
		6: "WORKFLOW_STATUS_QUEUED",
		7: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNKNOWN":   0,
		"WORKFLOW_STATUS_RUNNING":   1,
		"WORKFLOW_STATUS_COMPLETED": 2,
		"WORKFLOW_STATUS_FAILED":    3,
		"WORKFLOW_STATUS_SUSPENDED": 4,
		"WORKFLOW_STATUS_BACKOFF":   5,
		"WORKFLOW_STATUS_QUEUED":    6,
		"WORKFLOW_STATUS_CANCELLED": 7,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_protos_event_proto_enumTypes[2].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_flow_protos_event_proto_enumTypes[2]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{2}
}

// There are various kinds of events that are emitted during execution of a
// workflow. Each has a timestamp and a serial, ensuring that deterministic
// behavior can be verified.
//
// Every event also names the thread it belongs to. In the project this schema
// came from, threads were a map<string, Thread> inside the run and the whole run
// was rewritten on each checkpoint; here the run IS the stream of its events, so
// an event has to say where it belongs rather than being filed by its position
// in a blob. That is what lets a checkpoint be an append of one record instead
// of a rewrite of everything so far.
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Position of this event within its thread, counting from zero. Replay
	// consumes a thread's events in this order and compares each against what the
	// workflow function is doing now.
	Serial uint64 `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	// The run that produced this event. Events from an abandoned attempt stay in
	// the stream, so this is how a reader tells them apart.
	Attempt uint64 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// The thread this event belongs to. "main" is the thread the workflow
	// function itself runs on; forked threads are named "<parent>.<n>".
	ThreadId string `protobuf:"bytes,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Join
	//	*Event_Call
	//	*Event_Fork
	//	*Event_Sleep
	//	*Event_Time
	//	*Event_Return
	//	*Event_RunStart
	//	*Event_RunEnd
	//	*Event_ChannelSend
	//	*Event_ChannelRecv
	//	*Event_Effect
	//	*Event_Interrupted
	//	*Event_Select
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_flow_protos_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *Event) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Event) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetJoin() *JoinEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *Event) GetCall() *CallEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Event) GetFork() *ForkEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Fork); ok {
			return x.Fork
		}
	}
	return nil
}

func (x *Event) GetSleep() *SleepEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Sleep); ok {
			return x.Sleep
		}
	}
	return nil
}

func (x *Event) GetTime() *GetTimeEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Time); ok {
			return x.Time
		}
	}
	return nil
}

func (x *Event) GetReturn() *ReturnEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Event) GetRunStart() *RunStartEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunStart); ok {
			return x.RunStart
		}
	}
	return nil
}

func (x *Event) GetRunEnd() *RunEndEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunEnd); ok {
			return x.RunEnd
		}
	}
	return nil
}

func (x *Event) GetChannelSend() *ChannelSendEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ChannelSend); ok {
			return x.ChannelSend
		}
	}
	return nil
}

func (x *Event) GetChannelRecv() *ChannelRecvEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ChannelRecv); ok {
			return x.ChannelRecv
		}
	}
	return nil
}

func (x *Event) GetEffect() *EffectEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Effect); ok {
			return x.Effect
		}
	}
	return nil
}

func (x *Event) GetInterrupted() *WaitInterruptedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Interrupted); ok {
			return x.Interrupted
		}
	}
	return nil
}

func (x *Event) GetSelect() *SelectEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Select); ok {
			return x.Select
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Join struct {
	Join *JoinEvent `protobuf:"bytes,20,opt,name=join,proto3,oneof"`
}

type Event_Call struct {
	Call *CallEvent `protobuf:"bytes,21,opt,name=call,proto3,oneof"`
}

type Event_Fork struct {
	Fork *ForkEvent `protobuf:"bytes,22,opt,name=fork,proto3,oneof"`
}

type Event_Sleep struct {
	Sleep *SleepEvent `protobuf:"bytes,23,opt,name=sleep,proto3,oneof"`
}

type Event_Time struct {
	Time *GetTimeEvent `protobuf:"bytes,24,opt,name=time,proto3,oneof"`
}

type Event_Return struct {
	Return *ReturnEvent `protobuf:"bytes,25,opt,name=return,proto3,oneof"`
}

type Event_RunStart struct {
	RunStart *RunStartEvent `protobuf:"bytes,26,opt,name=run_start,json=runStart,proto3,oneof"`
}

type Event_RunEnd struct {
	RunEnd *RunEndEvent `protobuf:"bytes,27,opt,name=run_end,json=runEnd,proto3,oneof"`
}

type Event_ChannelSend struct {
	ChannelSend *ChannelSendEvent `protobuf:"bytes,28,opt,name=channel_send,json=channelSend,proto3,oneof"`
}

type Event_ChannelRecv struct {
	ChannelRecv *ChannelRecvEvent `protobuf:"bytes,29,opt,name=channel_recv,json=channelRecv,proto3,oneof"`
}

type Event_Effect struct {
	Effect *EffectEvent `protobuf:"bytes,30,opt,name=effect,proto3,oneof"`
}

type Event_Interrupted struct {
	Interrupted *WaitInterruptedEvent `protobuf:"bytes,31,opt,name=interrupted,proto3,oneof"`
}

type Event_Select struct {
	Select *SelectEvent `protobuf:"bytes,32,opt,name=select,proto3,oneof"`
}

func (*Event_Join) isEvent_Payload() {}

func (*Event_Call) isEvent_Payload() {}

func (*Event_Fork) isEvent_Payload() {}

func (*Event_Sleep) isEvent_Payload() {}

func (*Event_Time) isEvent_Payload() {}

func (*Event_Return) isEvent_Payload() {}

func (*Event_RunStart) isEvent_Payload() {}

func (*Event_RunEnd) isEvent_Payload() {}

func (*Event_ChannelSend) isEvent_Payload() {}

func (*Event_ChannelRecv) isEvent_Payload() {}

func (*Event_Effect) isEvent_Payload() {}

func (*Event_Interrupted) isEvent_Payload() {}

func (*Event_Select) isEvent_Payload() {}

type CallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params        *Data                  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{1}
}

func (x *CallEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallEvent) GetParams() *Data {
	if x != nil {
		return x.Params
	}
	return nil
}

// ForkEvent is a thread starting another. It carries the work the new thread
// is to do, so a reader of the parent's stream alone — an executor placing
// threads on machines — can start it: the function's name and its encoded
// input for a thread that runs one function, and neither for a thread that
// runs a piece of the run's own code, which only the process holding that
// code can run.
type ForkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent thread that is executing the fork
	ParentThreadId string `protobuf:"bytes,1,opt,name=parent_thread_id,json=parentThreadId,proto3" json:"parent_thread_id,omitempty"`
	// The thread id of the new thread
	ThreadId string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// The function the new thread runs, and its input. Empty for a thread that
	// runs a body of run code rather than a defined function.
	Function      string `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	Input         *Data  `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkEvent) Reset() {
	*x = ForkEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkEvent) ProtoMessage() {}

func (x *ForkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkEvent.ProtoReflect.Descriptor instead.
func (*ForkEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{2}
}

func (x *ForkEvent) GetParentThreadId() string {
	if x != nil {
		return x.ParentThreadId
	}
	return ""
}

func (x *ForkEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ForkEvent) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *ForkEvent) GetInput() *Data {
	if x != nil {
		return x.Input
	}
	return nil
}

// JoinEvent is a thread taking another's result, after which the other
// thread is over: the result is the parent's now, and a replay of the parent
// never starts the child again.
type JoinEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The thread id that is being joined
	ThreadId string `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// What the joined thread produced.
	Result        *Result `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEvent) Reset() {
	*x = JoinEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEvent) ProtoMessage() {}

func (x *JoinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEvent.ProtoReflect.Descriptor instead.
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{3}
}

func (x *JoinEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *JoinEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type SleepEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The duration for which the workflow is sleeping
	Duration      *durationpb.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepEvent) Reset() {
	*x = SleepEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepEvent) ProtoMessage() {}

func (x *SleepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepEvent.ProtoReflect.Descriptor instead.
func (*SleepEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{4}
}

func (x *SleepEvent) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type GetTimeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time at which the event was emitted
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeEvent) Reset() {
	*x = GetTimeEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeEvent) ProtoMessage() {}

func (x *GetTimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeEvent.ProtoReflect.Descriptor instead.
func (*GetTimeEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetTimeEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

// WaitInterruptedEvent is a wait — a join, a receive, a send, a close, a
// sleep — that a context the body made itself cut short: a timeout it set on
// the wait, a cancel it called. The body went on from there with the
// context's error, and the next attempt has to go on the same way, at once,
// rather than wait again for what the body already gave up on — or find
// that this time the wait would have completed, and diverge. A wait the
// thread's OWN context cut short is not recorded: the attempt is over.
type WaitInterruptedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which wait: "join", "recv", "send", "close" or "sleep", checked on
	// replay like every other event's shape.
	Wait string `protobuf:"bytes,1,opt,name=wait,proto3" json:"wait,omitempty"`
	// Why: the context's error.
	Cause         InterruptCause `protobuf:"varint,2,opt,name=cause,proto3,enum=wings.flow.v1.InterruptCause" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitInterruptedEvent) Reset() {
	*x = WaitInterruptedEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitInterruptedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitInterruptedEvent) ProtoMessage() {}

func (x *WaitInterruptedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitInterruptedEvent.ProtoReflect.Descriptor instead.
func (*WaitInterruptedEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{6}
}

func (x *WaitInterruptedEvent) GetWait() string {
	if x != nil {
		return x.Wait
	}
	return ""
}

func (x *WaitInterruptedEvent) GetCause() InterruptCause {
	if x != nil {
		return x.Cause
	}
	return InterruptCause_INTERRUPT_CAUSE_UNKNOWN
}

// SelectEvent records which case of a Context.Select won the race, so a replay
// takes the same one rather than whatever is ready first. The chosen case's own
// operation — a join, a receive — records separately, right after this.
type SelectEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The winning case, indexed in the order the cases were added.
	Chosen        uint64 `protobuf:"varint,1,opt,name=chosen,proto3" json:"chosen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectEvent) Reset() {
	*x = SelectEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectEvent) ProtoMessage() {}

func (x *SelectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectEvent.ProtoReflect.Descriptor instead.
func (*SelectEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{7}
}

func (x *SelectEvent) GetChosen() uint64 {
	if x != nil {
		return x.Chosen
	}
	return 0
}

type EffectEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the function passed to Context.Effect returned: its value, or its
	// error. Recorded so a replay hands back the same outcome instead of
	// running the function again.
	Result        *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectEvent) Reset() {
	*x = EffectEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectEvent) ProtoMessage() {}

func (x *EffectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectEvent.ProtoReflect.Descriptor instead.
func (*EffectEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{8}
}

func (x *EffectEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReturnEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result of the call
	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// The serial of the call event for which this is the return
	CallSerial    uint64 `protobuf:"varint,2,opt,name=call_serial,json=callSerial,proto3" json:"call_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnEvent) Reset() {
	*x = ReturnEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnEvent) ProtoMessage() {}

func (x *ReturnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnEvent.ProtoReflect.Descriptor instead.
func (*ReturnEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{9}
}

func (x *ReturnEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReturnEvent) GetCallSerial() uint64 {
	if x != nil {
		return x.CallSerial
	}
	return 0
}

// Channels let threads of one workflow pass typed values to each other. Two
// events, because a send and a receive are separately observable and only one of
// them is naturally deterministic.
//
// A thread's nth send on a channel always carries the same value, because the
// thread's own execution is deterministic — so a send needs recording only for
// WHEN it completed, which on an unbuffered channel depends on somebody
// receiving. A receive is the opposite: which value arrives first is decided by
// the operating system's scheduler, and nothing about the workflow determines
// it. So the receive records WHICH item it took, and a replay waits for exactly
// that one rather than taking whatever happens to be there.
type ChannelSendEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel's name, derived from the thread that created it.
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// This thread's nth send on this channel, counting from zero. Together with
	// the thread id it identifies one item for a receive to name.
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// What was sent. Not needed to replay — the sender recomputes it — but a
	// history that shows what actually flowed is worth the bytes.
	Value *Data `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Set when this closed the channel rather than sending. A close is a send in
	// every respect that matters here: it is a thing one thread does that another
	// observes, and it has to be ordered against the sends around it.
	Closed bool `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`
	// Set when the send found the channel already closed and was refused:
	// nothing was sent, and the sender was told so. Recorded, since the next
	// attempt must be told the same.
	Refused       bool `protobuf:"varint,5,opt,name=refused,proto3" json:"refused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelSendEvent) Reset() {
	*x = ChannelSendEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelSendEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelSendEvent) ProtoMessage() {}

func (x *ChannelSendEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelSendEvent.ProtoReflect.Descriptor instead.
func (*ChannelSendEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{10}
}

func (x *ChannelSendEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelSendEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChannelSendEvent) GetValue() *Data {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ChannelSendEvent) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *ChannelSendEvent) GetRefused() bool {
	if x != nil {
		return x.Refused
	}
	return false
}

type ChannelRecvEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Channel string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Which thread's send this took, and which of that thread's sends. Empty and
	// zero when the receive observed a closed channel instead.
	FromThreadId string `protobuf:"bytes,2,opt,name=from_thread_id,json=fromThreadId,proto3" json:"from_thread_id,omitempty"`
	FromSeq      uint64 `protobuf:"varint,3,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	// Set when the receive found the channel closed and drained, which is the
	// one outcome that yields no value.
	Closed bool `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`
	// What was received. Needed to replay: the sender may be a thread that has
	// since been joined, and a joined thread is not run again.
	Value         *Data `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRecvEvent) Reset() {
	*x = ChannelRecvEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRecvEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRecvEvent) ProtoMessage() {}

func (x *ChannelRecvEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRecvEvent.ProtoReflect.Descriptor instead.
func (*ChannelRecvEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelRecvEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelRecvEvent) GetFromThreadId() string {
	if x != nil {
		return x.FromThreadId
	}
	return ""
}

func (x *ChannelRecvEvent) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *ChannelRecvEvent) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *ChannelRecvEvent) GetValue() *Data {
	if x != nil {
		return x.Value
	}
	return nil
}

// RunStartEvent opens an attempt of a thread. Every thread has its own stream
// and its own attempts; workflow_name is the run, instance_id the thread. It carries everything needed to begin, so a
// reader of the stream alone can tell what was run and with what.
type RunStartEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Attempt      uint64                 `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Reason       StartReason            `protobuf:"varint,2,opt,name=reason,proto3,enum=wings.flow.v1.StartReason" json:"reason,omitempty"`
	WorkflowName string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	InstanceId   string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Version      uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Input        *Data                  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	// The function the thread runs, for a thread that runs one; empty for a
	// run's own body.
	Function      string `protobuf:"bytes,7,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStartEvent) Reset() {
	*x = RunStartEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStartEvent) ProtoMessage() {}

func (x *RunStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStartEvent.ProtoReflect.Descriptor instead.
func (*RunStartEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{12}
}

func (x *RunStartEvent) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RunStartEvent) GetReason() StartReason {
	if x != nil {
		return x.Reason
	}
	return StartReason_START_REASON_UNKNOWN
}

func (x *RunStartEvent) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunStartEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RunStartEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RunStartEvent) GetInput() *Data {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunStartEvent) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

// RunEndEvent closes an attempt, and says what became of it.
type RunEndEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=wings.flow.v1.WorkflowStatus" json:"status,omitempty"`
	Result *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// When the next attempt should begin, for a run that is backing off or
	// suspended. Unset otherwise.
	ScheduledFor  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEndEvent) Reset() {
	*x = RunEndEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEndEvent) ProtoMessage() {}

func (x *RunEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEndEvent.ProtoReflect.Descriptor instead.
func (*RunEndEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{13}
}

func (x *RunEndEvent) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNKNOWN
}

func (x *RunEndEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunEndEvent) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

var File_flow_protos_event_proto protoreflect.FileDescriptor

const file_flow_protos_event_proto_rawDesc = "" +
	"\n" +
	"\x17flow/protos/event.proto\x12\rwings.flow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x16flow/protos/data.proto\"\xfc\x06\n" +
	"\x05Event\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x04R\x06serial\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x04R\aattempt\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\tR\bthreadId\x12.\n" +
	"\x04join\x18\x14 \x01(\v2\x18.wings.flow.v1.JoinEventH\x00R\x04join\x12.\n" +
	"\x04call\x18\x15 \x01(\v2\x18.wings.flow.v1.CallEventH\x00R\x04call\x12.\n" +
	"\x04fork\x18\x16 \x01(\v2\x18.wings.flow.v1.ForkEventH\x00R\x04fork\x121\n" +
	"\x05sleep\x18\x17 \x01(\v2\x19.wings.flow.v1.SleepEventH\x00R\x05sleep\x121\n" +
	"\x04time\x18\x18 \x01(\v2\x1b.wings.flow.v1.GetTimeEventH\x00R\x04time\x124\n" +
	"\x06return\x18\x19 \x01(\v2\x1a.wings.flow.v1.ReturnEventH\x00R\x06return\x12;\n" +
	"\trun_start\x18\x1a \x01(\v2\x1c.wings.flow.v1.RunStartEventH\x00R\brunStart\x125\n" +
	"\arun_end\x18\x1b \x01(\v2\x1a.wings.flow.v1.RunEndEventH\x00R\x06runEnd\x12D\n" +
	"\fchannel_send\x18\x1c \x01(\v2\x1f.wings.flow.v1.ChannelSendEventH\x00R\vchannelSend\x12D\n" +
	"\fchannel_recv\x18\x1d \x01(\v2\x1f.wings.flow.v1.ChannelRecvEventH\x00R\vchannelRecv\x124\n" +
	"\x06effect\x18\x1e \x01(\v2\x1a.wings.flow.v1.EffectEventH\x00R\x06effect\x12G\n" +
	"\vinterrupted\x18\x1f \x01(\v2#.wings.flow.v1.WaitInterruptedEventH\x00R\vinterrupted\x124\n" +
	"\x06select\x18  \x01(\v2\x1a.wings.flow.v1.SelectEventH\x00R\x06selectB\t\n" +
	"\apayload\"L\n" +
	"\tCallEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06params\x18\x02 \x01(\v2\x13.wings.flow.v1.DataR\x06params\"\x99\x01\n" +
	"\tForkEvent\x12(\n" +
	"\x10parent_thread_id\x18\x01 \x01(\tR\x0eparentThreadId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\x12)\n" +
	"\x05input\x18\x04 \x01(\v2\x13.wings.flow.v1.DataR\x05input\"W\n" +
	"\tJoinEvent\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.wings.flow.v1.ResultR\x06result\"C\n" +
	"\n" +
	"SleepEvent\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\">\n" +
	"\fGetTimeEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"_\n" +
	"\x14WaitInterruptedEvent\x12\x12\n" +
	"\x04wait\x18\x01 \x01(\tR\x04wait\x123\n" +
	"\x05cause\x18\x02 \x01(\x0e2\x1d.wings.flow.v1.InterruptCauseR\x05cause\"%\n" +
	"\vSelectEvent\x12\x16\n" +
	"\x06chosen\x18\x01 \x01(\x04R\x06chosen\"<\n" +
	"\vEffectEvent\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.wings.flow.v1.ResultR\x06result\"]\n" +
	"\vReturnEvent\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.wings.flow.v1.ResultR\x06result\x12\x1f\n" +
	"\vcall_serial\x18\x02 \x01(\x04R\n" +
	"callSerial\"\x9b\x01\n" +
	"\x10ChannelSendEvent\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12)\n" +
	"\x05value\x18\x03 \x01(\v2\x13.wings.flow.v1.DataR\x05value\x12\x16\n" +
	"\x06closed\x18\x04 \x01(\bR\x06closed\x12\x18\n" +
	"\arefused\x18\x05 \x01(\bR\arefused\"\xb0\x01\n" +
	"\x10ChannelRecvEvent\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12$\n" +
	"\x0efrom_thread_id\x18\x02 \x01(\tR\ffromThreadId\x12\x19\n" +
	"\bfrom_seq\x18\x03 \x01(\x04R\afromSeq\x12\x16\n" +
	"\x06closed\x18\x04 \x01(\bR\x06closed\x12)\n" +
	"\x05value\x18\x05 \x01(\v2\x13.wings.flow.v1.DataR\x05value\"\x84\x02\n" +
	"\rRunStartEvent\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\x04R\aattempt\x122\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1a.wings.flow.v1.StartReasonR\x06reason\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x12)\n" +
	"\x05input\x18\x06 \x01(\v2\x13.wings.flow.v1.DataR\x05input\x12\x1a\n" +
	"\bfunction\x18\a \x01(\tR\bfunction\"\xb4\x01\n" +
	"\vRunEndEvent\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.wings.flow.v1.WorkflowStatusR\x06status\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.wings.flow.v1.ResultR\x06result\x12?\n" +
	"\rscheduled_for\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor*r\n" +
	"\x0eInterruptCause\x12\x1b\n" +
	"\x17INTERRUPT_CAUSE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18INTERRUPT_CAUSE_CANCELED\x10\x01\x12%\n" +
	"!INTERRUPT_CAUSE_DEADLINE_EXCEEDED\x10\x02*o\n" +
	"\vStartReason\x12\x18\n" +
	"\x14START_REASON_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11START_REASON_INIT\x10\x01\x12\x17\n" +
	"\x13START_REASON_RESUME\x10\x02\x12\x16\n" +
	"\x12START_REASON_RETRY\x10\x03*\xfc\x01\n" +
	"\x0eWorkflowStatus\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_SUSPENDED\x10\x04\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_BACKOFF\x10\x05\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_QUEUED\x10\x06\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\aB'Z%github.com/ligustah/wings/flow/protosb\x06proto3"

var (
	file_flow_protos_event_proto_rawDescOnce sync.Once
	file_flow_protos_event_proto_rawDescData []byte
)

func file_flow_protos_event_proto_rawDescGZIP() []byte {
	file_flow_protos_event_proto_rawDescOnce.Do(func() {
		file_flow_protos_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_protos_event_proto_rawDesc), len(file_flow_protos_event_proto_rawDesc)))
	})
	return file_flow_protos_event_proto_rawDescData
}

var file_flow_protos_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_flow_protos_event_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_flow_protos_event_proto_goTypes = []any{
	(InterruptCause)(0),           // 0: wings.flow.v1.InterruptCause
	(StartReason)(0),              // 1: wings.flow.v1.StartReason
	(WorkflowStatus)(0),           // 2: wings.flow.v1.WorkflowStatus
	(*Event)(nil),                 // 3: wings.flow.v1.Event
	(*CallEvent)(nil),             // 4: wings.flow.v1.CallEvent
	(*ForkEvent)(nil),             // 5: wings.flow.v1.ForkEvent
	(*JoinEvent)(nil),             // 6: wings.flow.v1.JoinEvent
	(*SleepEvent)(nil),            // 7: wings.flow.v1.SleepEvent
	(*GetTimeEvent)(nil),          // 8: wings.flow.v1.GetTimeEvent
	(*WaitInterruptedEvent)(nil),  // 9: wings.flow.v1.WaitInterruptedEvent
	(*SelectEvent)(nil),           // 10: wings.flow.v1.SelectEvent
	(*EffectEvent)(nil),           // 11: wings.flow.v1.EffectEvent
	(*ReturnEvent)(nil),           // 12: wings.flow.v1.ReturnEvent
	(*ChannelSendEvent)(nil),      // 13: wings.flow.v1.ChannelSendEvent
	(*ChannelRecvEvent)(nil),      // 14: wings.flow.v1.ChannelRecvEvent
	(*RunStartEvent)(nil),         // 15: wings.flow.v1.RunStartEvent
	(*RunEndEvent)(nil),           // 16: wings.flow.v1.RunEndEvent
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*Data)(nil),                  // 18: wings.flow.v1.Data
	(*Result)(nil),                // 19: wings.flow.v1.Result
	(*durationpb.Duration)(nil),   // 20: google.protobuf.Duration
}
var file_flow_protos_event_proto_depIdxs = []int32{
	17, // 0: wings.flow.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 1: wings.flow.v1.Event.join:type_name -> wings.flow.v1.JoinEvent
	4,  // 2: wings.flow.v1.Event.call:type_name -> wings.flow.v1.CallEvent
	5,  // 3: wings.flow.v1.Event.fork:type_name -> wings.flow.v1.ForkEvent
	7,  // 4: wings.flow.v1.Event.sleep:type_name -> wings.flow.v1.SleepEvent
	8,  // 5: wings.flow.v1.Event.time:type_name -> wings.flow.v1.GetTimeEvent
	12, // 6: wings.flow.v1.Event.return:type_name -> wings.flow.v1.ReturnEvent
	15, // 7: wings.flow.v1.Event.run_start:type_name -> wings.flow.v1.RunStartEvent
	16, // 8: wings.flow.v1.Event.run_end:type_name -> wings.flow.v1.RunEndEvent
	13, // 9: wings.flow.v1.Event.channel_send:type_name -> wings.flow.v1.ChannelSendEvent
	14, // 10: wings.flow.v1.Event.channel_recv:type_name -> wings.flow.v1.ChannelRecvEvent
	11, // 11: wings.flow.v1.Event.effect:type_name -> wings.flow.v1.EffectEvent
	9,  // 12: wings.flow.v1.Event.interrupted:type_name -> wings.flow.v1.WaitInterruptedEvent
	10, // 13: wings.flow.v1.Event.select:type_name -> wings.flow.v1.SelectEvent
	18, // 14: wings.flow.v1.CallEvent.params:type_name -> wings.flow.v1.Data
	18, // 15: wings.flow.v1.ForkEvent.input:type_name -> wings.flow.v1.Data
	19, // 16: wings.flow.v1.JoinEvent.result:type_name -> wings.flow.v1.Result
	20, // 17: wings.flow.v1.SleepEvent.duration:type_name -> google.protobuf.Duration
	17, // 18: wings.flow.v1.GetTimeEvent.time:type_name -> google.protobuf.Timestamp
	0,  // 19: wings.flow.v1.WaitInterruptedEvent.cause:type_name -> wings.flow.v1.InterruptCause
	19, // 20: wings.flow.v1.EffectEvent.result:type_name -> wings.flow.v1.Result
	19, // 21: wings.flow.v1.ReturnEvent.result:type_name -> wings.flow.v1.Result
	18, // 22: wings.flow.v1.ChannelSendEvent.value:type_name -> wings.flow.v1.Data
	18, // 23: wings.flow.v1.ChannelRecvEvent.value:type_name -> wings.flow.v1.Data
	1,  // 24: wings.flow.v1.RunStartEvent.reason:type_name -> wings.flow.v1.StartReason
	18, // 25: wings.flow.v1.RunStartEvent.input:type_name -> wings.flow.v1.Data
	2,  // 26: wings.flow.v1.RunEndEvent.status:type_name -> wings.flow.v1.WorkflowStatus
	19, // 27: wings.flow.v1.RunEndEvent.result:type_name -> wings.flow.v1.Result
	17, // 28: wings.flow.v1.RunEndEvent.scheduled_for:type_name -> google.protobuf.Timestamp
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_flow_protos_event_proto_init() }
func file_flow_protos_event_proto_init() {
	if File_flow_protos_event_proto != nil {
		return
	}
	file_flow_protos_data_proto_init()
	file_flow_protos_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Join)(nil),
		(*Event_Call)(nil),
		(*Event_Fork)(nil),
		(*Event_Sleep)(nil),
		(*Event_Time)(nil),
		(*Event_Return)(nil),
		(*Event_RunStart)(nil),
		(*Event_RunEnd)(nil),
		(*Event_ChannelSend)(nil),
		(*Event_ChannelRecv)(nil),
		(*Event_Effect)(nil),
		(*Event_Interrupted)(nil),
		(*Event_Select)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_protos_event_proto_rawDesc), len(file_flow_protos_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_protos_event_proto_goTypes,
		DependencyIndexes: file_flow_protos_event_proto_depIdxs,
		EnumInfos:         file_flow_protos_event_proto_enumTypes,
		MessageInfos:      file_flow_protos_event_proto_msgTypes,
	}.Build()
	File_flow_protos_event_proto = out.File
	file_flow_protos_event_proto_goTypes = nil
	file_flow_protos_event_proto_depIdxs = nil
}
