// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: flow/protos/event.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartReason int32

const (
	StartReason_START_REASON_UNKNOWN StartReason = 0
	StartReason_START_REASON_INIT    StartReason = 1
	StartReason_START_REASON_RESUME  StartReason = 2
	StartReason_START_REASON_RETRY   StartReason = 3
)

// Enum value maps for StartReason.
var (
	StartReason_name = map[int32]string{
		0: "START_REASON_UNKNOWN",
		1: "START_REASON_INIT",
		2: "START_REASON_RESUME",
		3: "START_REASON_RETRY",
	}
	StartReason_value = map[string]int32{
		"START_REASON_UNKNOWN": 0,
		"START_REASON_INIT":    1,
		"START_REASON_RESUME":  2,
		"START_REASON_RETRY":   3,
	}
)

func (x StartReason) Enum() *StartReason {
	p := new(StartReason)
	*p = x
	return p
}

func (x StartReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartReason) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_protos_event_proto_enumTypes[0].Descriptor()
}

func (StartReason) Type() protoreflect.EnumType {
	return &file_flow_protos_event_proto_enumTypes[0]
}

func (x StartReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartReason.Descriptor instead.
func (StartReason) EnumDescriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{0}
}

// *
// The `WorkflowStatus` enum represents the status of a workflow run.
type WorkflowStatus int32

const (
	// The status of the workflow is unknown. This is the default value.
	WorkflowStatus_WORKFLOW_STATUS_UNKNOWN WorkflowStatus = 0
	// The workflow is currently running.
	WorkflowStatus_WORKFLOW_STATUS_RUNNING WorkflowStatus = 1
	// The workflow has successfully finished.
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED WorkflowStatus = 2
	// The workflow has permanently failed to complete.
	WorkflowStatus_WORKFLOW_STATUS_FAILED WorkflowStatus = 3
	// The workflow is temporarily on hold.
	WorkflowStatus_WORKFLOW_STATUS_SUSPENDED WorkflowStatus = 4
	// The workflow is in backoff state due to a failed attempt.
	WorkflowStatus_WORKFLOW_STATUS_BACKOFF WorkflowStatus = 5
	// The workflow has been added to a queue, and is waiting to get executed.
	WorkflowStatus_WORKFLOW_STATUS_QUEUED WorkflowStatus = 6
	// The workflow has been cancelled.
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED WorkflowStatus = 7
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNKNOWN",
		1: "WORKFLOW_STATUS_RUNNING",
		2: "WORKFLOW_STATUS_COMPLETED",
		3: "WORKFLOW_STATUS_FAILED",
		4: "WORKFLOW_STATUS_SUSPENDED",
		5: "WORKFLOW_STATUS_BACKOFF",
		6: "WORKFLOW_STATUS_QUEUED",
		7: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNKNOWN":   0,
		"WORKFLOW_STATUS_RUNNING":   1,
		"WORKFLOW_STATUS_COMPLETED": 2,
		"WORKFLOW_STATUS_FAILED":    3,
		"WORKFLOW_STATUS_SUSPENDED": 4,
		"WORKFLOW_STATUS_BACKOFF":   5,
		"WORKFLOW_STATUS_QUEUED":    6,
		"WORKFLOW_STATUS_CANCELLED": 7,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_protos_event_proto_enumTypes[1].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_flow_protos_event_proto_enumTypes[1]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{1}
}

// There are various kinds of events that are emitted during execution of a
// workflow. Each has a timestamp and a serial, ensuring that deterministic
// behavior can be verified.
//
// Every event also names the thread it belongs to. In the project this schema
// came from, threads were a map<string, Thread> inside the run and the whole run
// was rewritten on each checkpoint; here the run IS the stream of its events, so
// an event has to say where it belongs rather than being filed by its position
// in a blob. That is what lets a checkpoint be an append of one record instead
// of a rewrite of everything so far.
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Position of this event within its thread, counting from zero. Replay
	// consumes a thread's events in this order and compares each against what the
	// workflow function is doing now.
	Serial uint64 `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	// The run that produced this event. Events from an abandoned attempt stay in
	// the stream, so this is how a reader tells them apart.
	Attempt uint64 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// The thread this event belongs to. "main" is the thread the workflow
	// function itself runs on; forked threads are named "<parent>.<n>".
	ThreadId string `protobuf:"bytes,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Join
	//	*Event_Call
	//	*Event_Fork
	//	*Event_Sleep
	//	*Event_Time
	//	*Event_Return
	//	*Event_RunStart
	//	*Event_RunEnd
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_flow_protos_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *Event) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Event) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetJoin() *JoinEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *Event) GetCall() *CallEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Event) GetFork() *ForkEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Fork); ok {
			return x.Fork
		}
	}
	return nil
}

func (x *Event) GetSleep() *SleepEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Sleep); ok {
			return x.Sleep
		}
	}
	return nil
}

func (x *Event) GetTime() *GetTimeEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Time); ok {
			return x.Time
		}
	}
	return nil
}

func (x *Event) GetReturn() *ReturnEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Event) GetRunStart() *RunStartEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunStart); ok {
			return x.RunStart
		}
	}
	return nil
}

func (x *Event) GetRunEnd() *RunEndEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunEnd); ok {
			return x.RunEnd
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Join struct {
	Join *JoinEvent `protobuf:"bytes,20,opt,name=join,proto3,oneof"`
}

type Event_Call struct {
	Call *CallEvent `protobuf:"bytes,21,opt,name=call,proto3,oneof"`
}

type Event_Fork struct {
	Fork *ForkEvent `protobuf:"bytes,22,opt,name=fork,proto3,oneof"`
}

type Event_Sleep struct {
	Sleep *SleepEvent `protobuf:"bytes,23,opt,name=sleep,proto3,oneof"`
}

type Event_Time struct {
	Time *GetTimeEvent `protobuf:"bytes,24,opt,name=time,proto3,oneof"`
}

type Event_Return struct {
	Return *ReturnEvent `protobuf:"bytes,25,opt,name=return,proto3,oneof"`
}

type Event_RunStart struct {
	RunStart *RunStartEvent `protobuf:"bytes,26,opt,name=run_start,json=runStart,proto3,oneof"`
}

type Event_RunEnd struct {
	RunEnd *RunEndEvent `protobuf:"bytes,27,opt,name=run_end,json=runEnd,proto3,oneof"`
}

func (*Event_Join) isEvent_Payload() {}

func (*Event_Call) isEvent_Payload() {}

func (*Event_Fork) isEvent_Payload() {}

func (*Event_Sleep) isEvent_Payload() {}

func (*Event_Time) isEvent_Payload() {}

func (*Event_Return) isEvent_Payload() {}

func (*Event_RunStart) isEvent_Payload() {}

func (*Event_RunEnd) isEvent_Payload() {}

type CallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params        *Data                  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{1}
}

func (x *CallEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallEvent) GetParams() *Data {
	if x != nil {
		return x.Params
	}
	return nil
}

type ForkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent thread that is executing the fork
	ParentThreadId string `protobuf:"bytes,1,opt,name=parent_thread_id,json=parentThreadId,proto3" json:"parent_thread_id,omitempty"`
	// The thread id of the new thread
	ThreadId      string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkEvent) Reset() {
	*x = ForkEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkEvent) ProtoMessage() {}

func (x *ForkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkEvent.ProtoReflect.Descriptor instead.
func (*ForkEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{2}
}

func (x *ForkEvent) GetParentThreadId() string {
	if x != nil {
		return x.ParentThreadId
	}
	return ""
}

func (x *ForkEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type JoinEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The thread id that is being joined
	ThreadId      string `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEvent) Reset() {
	*x = JoinEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEvent) ProtoMessage() {}

func (x *JoinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEvent.ProtoReflect.Descriptor instead.
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{3}
}

func (x *JoinEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type SleepEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The duration for which the workflow is sleeping
	Duration      *durationpb.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepEvent) Reset() {
	*x = SleepEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepEvent) ProtoMessage() {}

func (x *SleepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepEvent.ProtoReflect.Descriptor instead.
func (*SleepEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{4}
}

func (x *SleepEvent) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type GetTimeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time at which the event was emitted
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeEvent) Reset() {
	*x = GetTimeEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeEvent) ProtoMessage() {}

func (x *GetTimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeEvent.ProtoReflect.Descriptor instead.
func (*GetTimeEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetTimeEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type ReturnEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result of the call
	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// The serial of the call event for which this is the return
	CallSerial    uint64 `protobuf:"varint,2,opt,name=call_serial,json=callSerial,proto3" json:"call_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnEvent) Reset() {
	*x = ReturnEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnEvent) ProtoMessage() {}

func (x *ReturnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnEvent.ProtoReflect.Descriptor instead.
func (*ReturnEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{6}
}

func (x *ReturnEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReturnEvent) GetCallSerial() uint64 {
	if x != nil {
		return x.CallSerial
	}
	return 0
}

// RunStartEvent opens an attempt. It carries everything needed to begin, so a
// reader of the stream alone can tell what was run and with what.
type RunStartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       uint64                 `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Reason        StartReason            `protobuf:"varint,2,opt,name=reason,proto3,enum=wings.flow.v1.StartReason" json:"reason,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Input         *Data                  `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStartEvent) Reset() {
	*x = RunStartEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStartEvent) ProtoMessage() {}

func (x *RunStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStartEvent.ProtoReflect.Descriptor instead.
func (*RunStartEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{7}
}

func (x *RunStartEvent) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RunStartEvent) GetReason() StartReason {
	if x != nil {
		return x.Reason
	}
	return StartReason_START_REASON_UNKNOWN
}

func (x *RunStartEvent) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunStartEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RunStartEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RunStartEvent) GetInput() *Data {
	if x != nil {
		return x.Input
	}
	return nil
}

// RunEndEvent closes an attempt, and says what became of it.
type RunEndEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status WorkflowStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=wings.flow.v1.WorkflowStatus" json:"status,omitempty"`
	Result *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	// When the next attempt should begin, for a run that is backing off or
	// suspended. Unset otherwise.
	ScheduledFor  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEndEvent) Reset() {
	*x = RunEndEvent{}
	mi := &file_flow_protos_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEndEvent) ProtoMessage() {}

func (x *RunEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_protos_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEndEvent.ProtoReflect.Descriptor instead.
func (*RunEndEvent) Descriptor() ([]byte, []int) {
	return file_flow_protos_event_proto_rawDescGZIP(), []int{8}
}

func (x *RunEndEvent) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNKNOWN
}

func (x *RunEndEvent) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunEndEvent) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

var File_flow_protos_event_proto protoreflect.FileDescriptor

const file_flow_protos_event_proto_rawDesc = "" +
	"\n" +
	"\x17flow/protos/event.proto\x12\rwings.flow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x16flow/protos/data.proto\"\xbb\x04\n" +
	"\x05Event\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x04R\x06serial\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x04R\aattempt\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\tR\bthreadId\x12.\n" +
	"\x04join\x18\x14 \x01(\v2\x18.wings.flow.v1.JoinEventH\x00R\x04join\x12.\n" +
	"\x04call\x18\x15 \x01(\v2\x18.wings.flow.v1.CallEventH\x00R\x04call\x12.\n" +
	"\x04fork\x18\x16 \x01(\v2\x18.wings.flow.v1.ForkEventH\x00R\x04fork\x121\n" +
	"\x05sleep\x18\x17 \x01(\v2\x19.wings.flow.v1.SleepEventH\x00R\x05sleep\x121\n" +
	"\x04time\x18\x18 \x01(\v2\x1b.wings.flow.v1.GetTimeEventH\x00R\x04time\x124\n" +
	"\x06return\x18\x19 \x01(\v2\x1a.wings.flow.v1.ReturnEventH\x00R\x06return\x12;\n" +
	"\trun_start\x18\x1a \x01(\v2\x1c.wings.flow.v1.RunStartEventH\x00R\brunStart\x125\n" +
	"\arun_end\x18\x1b \x01(\v2\x1a.wings.flow.v1.RunEndEventH\x00R\x06runEndB\t\n" +
	"\apayload\"L\n" +
	"\tCallEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06params\x18\x02 \x01(\v2\x13.wings.flow.v1.DataR\x06params\"R\n" +
	"\tForkEvent\x12(\n" +
	"\x10parent_thread_id\x18\x01 \x01(\tR\x0eparentThreadId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"(\n" +
	"\tJoinEvent\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"C\n" +
	"\n" +
	"SleepEvent\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\">\n" +
	"\fGetTimeEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"]\n" +
	"\vReturnEvent\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.wings.flow.v1.ResultR\x06result\x12\x1f\n" +
	"\vcall_serial\x18\x02 \x01(\x04R\n" +
	"callSerial\"\xe8\x01\n" +
	"\rRunStartEvent\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\x04R\aattempt\x122\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1a.wings.flow.v1.StartReasonR\x06reason\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x12)\n" +
	"\x05input\x18\x06 \x01(\v2\x13.wings.flow.v1.DataR\x05input\"\xb4\x01\n" +
	"\vRunEndEvent\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.wings.flow.v1.WorkflowStatusR\x06status\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.wings.flow.v1.ResultR\x06result\x12?\n" +
	"\rscheduled_for\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor*o\n" +
	"\vStartReason\x12\x18\n" +
	"\x14START_REASON_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11START_REASON_INIT\x10\x01\x12\x17\n" +
	"\x13START_REASON_RESUME\x10\x02\x12\x16\n" +
	"\x12START_REASON_RETRY\x10\x03*\xfc\x01\n" +
	"\x0eWorkflowStatus\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_SUSPENDED\x10\x04\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_BACKOFF\x10\x05\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_QUEUED\x10\x06\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\aB'Z%github.com/ligustah/wings/flow/protosb\x06proto3"

var (
	file_flow_protos_event_proto_rawDescOnce sync.Once
	file_flow_protos_event_proto_rawDescData []byte
)

func file_flow_protos_event_proto_rawDescGZIP() []byte {
	file_flow_protos_event_proto_rawDescOnce.Do(func() {
		file_flow_protos_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_protos_event_proto_rawDesc), len(file_flow_protos_event_proto_rawDesc)))
	})
	return file_flow_protos_event_proto_rawDescData
}

var file_flow_protos_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flow_protos_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_flow_protos_event_proto_goTypes = []any{
	(StartReason)(0),              // 0: wings.flow.v1.StartReason
	(WorkflowStatus)(0),           // 1: wings.flow.v1.WorkflowStatus
	(*Event)(nil),                 // 2: wings.flow.v1.Event
	(*CallEvent)(nil),             // 3: wings.flow.v1.CallEvent
	(*ForkEvent)(nil),             // 4: wings.flow.v1.ForkEvent
	(*JoinEvent)(nil),             // 5: wings.flow.v1.JoinEvent
	(*SleepEvent)(nil),            // 6: wings.flow.v1.SleepEvent
	(*GetTimeEvent)(nil),          // 7: wings.flow.v1.GetTimeEvent
	(*ReturnEvent)(nil),           // 8: wings.flow.v1.ReturnEvent
	(*RunStartEvent)(nil),         // 9: wings.flow.v1.RunStartEvent
	(*RunEndEvent)(nil),           // 10: wings.flow.v1.RunEndEvent
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*Data)(nil),                  // 12: wings.flow.v1.Data
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*Result)(nil),                // 14: wings.flow.v1.Result
}
var file_flow_protos_event_proto_depIdxs = []int32{
	11, // 0: wings.flow.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 1: wings.flow.v1.Event.join:type_name -> wings.flow.v1.JoinEvent
	3,  // 2: wings.flow.v1.Event.call:type_name -> wings.flow.v1.CallEvent
	4,  // 3: wings.flow.v1.Event.fork:type_name -> wings.flow.v1.ForkEvent
	6,  // 4: wings.flow.v1.Event.sleep:type_name -> wings.flow.v1.SleepEvent
	7,  // 5: wings.flow.v1.Event.time:type_name -> wings.flow.v1.GetTimeEvent
	8,  // 6: wings.flow.v1.Event.return:type_name -> wings.flow.v1.ReturnEvent
	9,  // 7: wings.flow.v1.Event.run_start:type_name -> wings.flow.v1.RunStartEvent
	10, // 8: wings.flow.v1.Event.run_end:type_name -> wings.flow.v1.RunEndEvent
	12, // 9: wings.flow.v1.CallEvent.params:type_name -> wings.flow.v1.Data
	13, // 10: wings.flow.v1.SleepEvent.duration:type_name -> google.protobuf.Duration
	11, // 11: wings.flow.v1.GetTimeEvent.time:type_name -> google.protobuf.Timestamp
	14, // 12: wings.flow.v1.ReturnEvent.result:type_name -> wings.flow.v1.Result
	0,  // 13: wings.flow.v1.RunStartEvent.reason:type_name -> wings.flow.v1.StartReason
	12, // 14: wings.flow.v1.RunStartEvent.input:type_name -> wings.flow.v1.Data
	1,  // 15: wings.flow.v1.RunEndEvent.status:type_name -> wings.flow.v1.WorkflowStatus
	14, // 16: wings.flow.v1.RunEndEvent.result:type_name -> wings.flow.v1.Result
	11, // 17: wings.flow.v1.RunEndEvent.scheduled_for:type_name -> google.protobuf.Timestamp
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_flow_protos_event_proto_init() }
func file_flow_protos_event_proto_init() {
	if File_flow_protos_event_proto != nil {
		return
	}
	file_flow_protos_data_proto_init()
	file_flow_protos_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Join)(nil),
		(*Event_Call)(nil),
		(*Event_Fork)(nil),
		(*Event_Sleep)(nil),
		(*Event_Time)(nil),
		(*Event_Return)(nil),
		(*Event_RunStart)(nil),
		(*Event_RunEnd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_protos_event_proto_rawDesc), len(file_flow_protos_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_protos_event_proto_goTypes,
		DependencyIndexes: file_flow_protos_event_proto_depIdxs,
		EnumInfos:         file_flow_protos_event_proto_enumTypes,
		MessageInfos:      file_flow_protos_event_proto_msgTypes,
	}.Build()
	File_flow_protos_event_proto = out.File
	file_flow_protos_event_proto_goTypes = nil
	file_flow_protos_event_proto_depIdxs = nil
}
