package main

import (
	"bytes"
	"fmt"

	"github.com/dave/jennifer/jen"
)

// The two generated programs, built with jennifer rather than assembled from
// string fragments.
//
// Not only tidiness: jennifer tracks imports, so adding a call to a package is
// one Qual and the import list follows, and it renders through go/format — a
// mistake here is a compile error in THIS file rather than syntactically broken
// output that fails inside a build the user never sees the source of.

const (
	generatedBy = `Code generated by "wings build"; DO NOT EDIT.`
	// wingsPkg is imported by both generated mains.
	wingsPkg = "github.com/ligustah/wings"
)

// workerMain generates the worker program:
//
//	package main
//
//	import (
//		_ "<work package>"
//		"github.com/ligustah/wings"
//	)
//
//	func main() { wings.WorkerMain() }
//
// The work package is imported for its side effects alone: its package-scope
// Define calls are what put the work functions in this process's registry, and
// that is the whole reason a worker binary can run code it holds no other
// reference to.
func workerMain(workPkg string) ([]byte, error) {
	f := jen.NewFile("main")
	f.HeaderComment(generatedBy)

	f.Comment("Imported for its Define calls, which register the work functions")
	f.Comment("this worker will be asked to run.")
	f.Anon(workPkg)

	f.Func().Id("main").Params().Block(
		jen.Qual(wingsPkg, "WorkerMain").Call(),
	)
	return render(f)
}

// coordinatorMain generates the coordinator program:
//
//	package main
//
//	import (
//		_ "embed"
//		app "<coordinator package>"
//		"github.com/ligustah/wings"
//	)
//
//	//go:embed wings_worker.bin.gz
//	var wingsWorker []byte
//
//	func main() {
//		wings.CoordinatorMain(wings.CoordinatorOptions{…})
//	}
//
// The coordinator package is imported for its DefineWorkflow calls, and by
// name only when it also exports a Provisioner the main has to call.
func coordinatorMain(workPkg, coordPkg string, worker platform, hasProvisioner bool, providers []string) ([]byte, error) {
	f := jen.NewFile("main")
	f.HeaderComment(generatedBy)

	// embed contributes nothing but the directive's machinery.
	f.Anon("embed")
	if hasProvisioner {
		f.ImportAlias(coordPkg, "app")
	} else {
		// Nothing in main names the package, so an aliased import would be
		// dropped as unused — and with it the workflows. Import it for effect.
		f.Comment("Linked in for its DefineWorkflow calls; the coordinator runs one of them.")
		f.Anon(coordPkg)
	}

	if workPkg != coordPkg {
		// Split build: the work package must still be linked in, because the
		// coordinator encodes and dispatches against the functions it defines.
		f.Comment("Linked in for its Define calls; the coordinator dispatches against them.")
		f.Anon(workPkg)
	}

	if len(providers) > 0 {
		// Imported for effect, the way a database driver is: each registers
		// itself and its flags, so -provider can name it. Only the COORDINATOR
		// links these — a worker provisions nothing and would carry a cloud SDK
		// for no reason.
		f.Comment("Each registers itself with wings, making it selectable with -provider.")
		for _, p := range providers {
			f.Anon(p)
		}
	}

	// The comment and the var must be ONE statement. //go:embed applies to the
	// declaration immediately below it, and a blank line between them silently
	// demotes the directive to an ordinary comment — the binary then builds
	// fine and carries no worker at all.
	f.Add(
		jen.Comment("//go:embed " + blobName).Line().
			Var().Id("wingsWorker").Index().Byte(),
	)

	f.Func().Id("main").Params().Block(
		jen.Qual(wingsPkg, "CoordinatorMain").Call(
			jen.Qual(wingsPkg, "CoordinatorOptions").Values(jen.Dict{
				jen.Id("Worker"):      jen.Id("wingsWorker"),
				jen.Id("WorkerOS"):    jen.Lit(worker.os),
				jen.Id("WorkerArch"):  jen.Lit(worker.arch),
				jen.Id("Provisioner"): provisionerValue(coordPkg, hasProvisioner),
			}),
		),
	)
	return render(f)
}

// provisionerValue is the Provisioner field's value, or nil when the package
// exports none — a nil field is how CoordinatorMain knows to refuse
// -target=remote with a sentence naming the function to add.
func provisionerValue(coordPkg string, has bool) jen.Code {
	if !has {
		return jen.Nil()
	}
	return jen.Qual(coordPkg, "Provisioner").Call()
}

func render(f *jen.File) ([]byte, error) {
	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("render generated source: %w", err)
	}
	return buf.Bytes(), nil
}
