package main

import (
	"bytes"
	"fmt"

	"github.com/dave/jennifer/jen"
)

// The two generated programs, built with jennifer so imports track
// automatically and a mistake is a compile error here.

const (
	generatedBy = `Code generated by "wings build"; DO NOT EDIT.`
	wingsPkg    = "github.com/ligustah/wings"
	flowPkg     = wingsPkg + "/flow"
)

// registerNames renders the flow.RegisterCallSiteNames call that names nameless
// Define calls from their variables; empty names emit nothing. It must run
// before any work, so it is the first statement of main.
func registerNames(names map[string]string) jen.Code {
	if len(names) == 0 {
		return jen.Null()
	}
	entries := jen.Dict{}
	for site, name := range names {
		entries[jen.Lit(site)] = jen.Lit(name)
	}
	return jen.Qual(flowPkg, "RegisterCallSiteNames").Call(
		jen.Map(jen.String()).String().Values(entries),
	).Line()
}

// workerMain generates the worker program: a blank import of the work package
// for its Define calls, and a main that calls wings.WorkerMain.
func workerMain(workPkg string, names map[string]string) ([]byte, error) {
	f := jen.NewFile("main")
	f.HeaderComment(generatedBy)

	f.Comment("Imported for its Define calls, which register the work functions")
	f.Comment("this worker will be asked to run.")
	f.Anon(workPkg)

	f.Func().Id("main").Params().Block(
		registerNames(names),
		jen.Qual(wingsPkg, "WorkerMain").Call(),
	)
	return render(f)
}

// coordinatorMain generates the coordinator program: it imports the coordinator
// package for its flow.Main calls (by name when it exports a Provisioner),
// embeds the worker blob, and calls wings.CoordinatorMain.
func coordinatorMain(workPkg, coordPkg string, worker platform, hasProvisioner bool, providers []string, names map[string]string) ([]byte, error) {
	f := jen.NewFile("main")
	f.HeaderComment(generatedBy)

	f.Anon("embed")
	if hasProvisioner {
		f.ImportAlias(coordPkg, "app")
	} else {
		// Blank import: nothing names the package, so an alias would be dropped.
		f.Comment("Linked in for its flow.Main calls; the coordinator runs one of them.")
		f.Anon(coordPkg)
	}

	if workPkg != coordPkg {
		f.Comment("Linked in for its Define calls; the coordinator dispatches against them.")
		f.Anon(workPkg)
	}

	if len(providers) > 0 {
		f.Comment("Each registers itself with wings, making it selectable with -provider.")
		for _, p := range providers {
			f.Anon(p)
		}
	}

	// The //go:embed comment and its var must be one statement: a blank line
	// between them demotes the directive, and the binary then carries no worker.
	f.Add(
		jen.Comment("//go:embed " + blobName).Line().
			Var().Id("wingsWorker").Index().Byte(),
	)

	f.Func().Id("main").Params().Block(
		registerNames(names),
		jen.Qual(wingsPkg, "CoordinatorMain").Call(
			jen.Qual(wingsPkg, "CoordinatorOptions").Values(jen.Dict{
				jen.Id("Worker"):      jen.Id("wingsWorker"),
				jen.Id("WorkerOS"):    jen.Lit(worker.os),
				jen.Id("WorkerArch"):  jen.Lit(worker.arch),
				jen.Id("Provisioner"): provisionerValue(coordPkg, hasProvisioner),
			}),
		),
	)
	return render(f)
}

// provisionerValue is the Provisioner field's value, or nil when the package
// exports none — which is how CoordinatorMain knows to refuse -target=remote.
func provisionerValue(coordPkg string, has bool) jen.Code {
	if !has {
		return jen.Nil()
	}
	return jen.Qual(coordPkg, "Provisioner").Call()
}

func render(f *jen.File) ([]byte, error) {
	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return nil, fmt.Errorf("render generated source: %w", err)
	}
	return buf.Bytes(), nil
}
